version: '3'

services:
  # PostgreSQL Database
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: database
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Django Web Application
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: 5432
      DJANGO_DB_NAME: postgres
      DJANGO_DB_USER: postgres
      DJANGO_DB_PASSWORD: database
      DJANGO_DEBUG: "True"
      DJANGO_REDIS_CACHE_URL: "redis://redis:6379/1"

  # Redis Server
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  # Celery Worker
  worker:
    build: .
    command: celery -A project worker --loglevel=info
    volumes:
      - ./project:/app
    depends_on:
      - db
      - redis
    environment:
      CELERY_BROKER_URL: redis://redis:6379/1
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: 5432
      DJANGO_DB_NAME: postgres
      DJANGO_DB_USER: postgres
      DJANGO_DB_PASSWORD: database
      DJANGO_DEBUG: "True"

  # Celery Flower Server
  flower:
    build: .
    command: celery -A project flower --port=5555
    volumes:
      - ./project:/app
    ports:
      - "5555:5555"
    depends_on:
      - db
      - redis
    environment:
      CELERY_BROKER_URL: redis://redis:6379/1
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: 5432
      DJANGO_DB_NAME: postgres
      DJANGO_DB_USER: postgres
      DJANGO_DB_PASSWORD: database
      DJANGO_DEBUG: "True"

volumes:
  postgres_data:
